development:
  adapter: postgresql
  encoding: unicode
  database: dl_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: dl_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: dl_production
  pool: 5
